FROM tiltr/base-dev:latest

LABEL Description="This ROS Kinetic image adds cartographer to tiltr base-dev" Version="1.0"

ENV HOME_DIR=/home/user
ENV PROJECTS_WS=$HOME_DIR/projects/wheely_good_robot/catkin_ws
ENV MY_USERNAME=user
USER $MY_USERNAME

RUN set +x && \
    \
    echo "Creating download links for test bags and launch files/scripts..." && \
    echo "wget -P ~/Downloads https://storage.googleapis.com/cartographer-public-data/bags/backpack_2d/cartographer_paper_deutsches_museum.bag" >> $HOME_DIR/download_test_bag.sh && \
    chmod +x $HOME_DIR/download_test_bag.sh && \
    echo "roslaunch cartographer_ros demo_backpack_2d.launch bag_filename:=${HOME}/Downloads/cartographer_paper_deutsches_museum.bag" >> $HOME_DIR/run_demo.sh && \
    chmod +x $HOME_DIR/run_demo.sh && \
    echo "wget -P ~/Downloads https://github.com/ElliWhite/proj515_ws/raw/master/map/303/303_pushing.bag" >> $HOME_DIR/download_303_bag.sh && \    
    echo "roslaunch cartographer_ros play_2d_scan.launch bag_filename:=${HOME}/Downloads/303_pushing.bag" >> $HOME_DIR/run_303_bag.sh && \    
    chmod +x $HOME_DIR/run_303_bag.sh && \        
    chmod +x $HOME_DIR/download_303_bag.sh && \            
    \
    echo "Installing apt package(s)" && \
    sudo apt-get update && \
    sudo apt-get install -y ros-kinetic-rplidar-ros && \
    \
    echo "Merging cartographer .rosinstall" && \
    cd $PROJECTS_WS && \
    wstool merge -t src https://raw.githubusercontent.com/carebare47/cartographer_ros/master/cartographer_ros.rosinstall && \
    \
    echo "Installing cartographers ROS dependencies via rosdep..." && \
    wstool update -t src && \
    src/cartographer/scripts/install_proto3.sh && \
    sudo rm -rf /etc/ros/rosdep/sources.list.d/20-default.list && \
    sudo rosdep init || exit 0 && \        
    rosdep update && \
    cd $PROJECTS_WS && \    
    source /opt/ros/kinetic/setup.bash && \
    rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y && \
    echo "Installing cartographer (catkin_make_isolated)..." && \
    \
    echo "source $PROJECTS_WS/install_isolated/setup.bash" >> $HOME_DIR/.bashrc && \
    cd $PROJECTS_WS && \
    catkin_make_isolated --install --use-ninja && \
    \
    echo "Downloading test bags..." && \
    cd $HOME_DIR && \
    ./download_test_bag.sh && \
    ./download_303_bag.sh


USER root

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/usr/bin/terminator"]
