FROM shadowrobot/build-tools:xenial-kinetic-ide

LABEL Description="This ROS Kinetic image contains Toms latest attempt at an autonomous mobile manipulator" Version="1.0"

ENV HOME_DIR=/home/user
ENV PROJECTS_WS=$HOME_DIR/projects/wheely_good_robot/catkin_ws
ENV remote_shell_script=bit.ly/tom_setup
ENV MY_USERNAME=user
USER $MY_USERNAME

RUN set +x && \
    \
    echo "Running tom_setup..." && \
    wget -O /tmp/tom_setup "$( echo "$remote_shell_script" | sed 's/#/%23/g' )" && \
    chmod +x /tmp/tom_setup && \
    bash -c /tmp/tom_setup --container true && \
    \
    echo "Creating and initialising the workspace..." && \
    mkdir -p $PROJECTS_WS && \
    sudo apt-get update && \
    sudo apt-get install -y python-wstool python-rosdep ninja-build && \
    cd $PROJECTS_WS && \
    wstool init src && \
    wstool update -t src
    
RUN set +x && \        
    sudo rosdep init; exit 0
    
RUN set +x && \        
    rosdep update && \
    \
    cd $PROJECTS_WS && \    
    rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y && \
    \
    cd $PROJECTS_WS && \    
    source /opt/ros/kinetic/setup.bash && \
    echo "source /opt/ros/kinetic/setup.bash" >> $HOME_DIR/.bashrc && \
    echo "source $PROJECTS_WS/install_isolated/setup.bash" >> $HOME_DIR/.bashrc && \
    \
    echo "Adding user to dialout group..." && \
    sudo usermod -a -G dialout $MY_USERNAME

ENV PATH="/home/user/arduino-1.8.9/bin:${PATH}"
RUN set +x && \        
    cd ~/ && wget https://downloads.arduino.cc/arduino-1.8.9-linux64.tar.xz && \
    tar -xJf arduino-1.8.9-linux64.tar.xz && \
    rm arduino-1.8.9-linux64.tar.xz && \
    cd arduino-1.8.9 && \	
    sudo ./install.sh && \    
    curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh && \
    touch $HOME_DIR/arduino-1.8.9/bin/arduino-cli.yaml && \
    echo -e "board_manager:\n additional_urls:\n   - https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json" >> $HOME_DIR/arduino-1.8.9/bin/arduino-cli.yaml && \
    cd $HOME_DIR/arduino-1.8.9/bin/ && \
    arduino-cli core update-index && \
    arduino-cli core install STM32:stm32 && \
    mkdir -p ~/Arduino/libraries && \
    cd ~/Arduino/libraries && \
    wget https://raw.githubusercontent.com/tiltr/tiltr-firmware/master/libraries && \
    while read repo; do git clone "$repo"; done < libraries && \
    cd bipropellant-hoverboard-api && git checkout master_arduino && cd .. && \
    echo "hacky library installation, improve this in dockerfile!" && \
    cd ~/Arduino/libraries && \
    git clone https://github.com/jrowberg/i2cdevlib && \
    cp -r i2cdevlib/Arduino/I2Cdev/ . && \
    cp -r i2cdevlib/Arduino/MPU6060/ . && \
    rm -rf i2cdevlib && \
    cd ~/Arduino && \
    git clone https://github.com/tiltr/tiltr-firmware 


USER root

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/usr/bin/terminator"]
